version: "3.5"

services:
  tweet_notifier:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CONSUMER_KEY: ${CONSUMER_KEY}
      CONSUMER_SECRET: ${CONSUMER_SECRET}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      ACCESS_SECRET: ${ACCESS_SECRET}
      PRIMARY_DISCORD_WEBHOOK_URL: ${PRIMARY_DISCORD_WEBHOOK_URL}
      SECONDARY_DISCORD_WEBHOOK_URL: ${SECONDARY_DISCORD_WEBHOOK_URL}
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      TWITCH_OAUTH_TOKEN: ${TWITCH_OAUTH_TOKEN}
      TWITCH_CLIENT_ID: ${TWITCH_CLIENT_ID}
      ELON_TWITTER_ACCOUNT_ID: "44196397"
      DELTAONE_TWITTER_ACCOUNT_ID: "2704294333"
      FIRSTSQUAWK_TWITTER_ACCOUNT_ID: "3295423333"
      LIVESQUAWK_TWITTER_ACCOUNT_ID: "59393368"
      DB_TWITTER_ACCOUNT_ID: "2361601055"
      WHALEALERT_TWITTER_ACCOUNT_ID: "1039833297751302144"
